const Birds = () => {
  return {
    aves: [
      'Aguia',
      'Albatroz',
      'Andorinha',
      'Anu',
      'Arara',
      'Beija flor',
      'Bigodinho',
      'Caboclinho',
      'Canario',
      'Carcara',
      'Condor',
      'Coruja',
      'Curio',
      'Emu',
      'Falcao',
      'Flamingo',
      'Frango',
      'Gaivota',
      'Galo',
      'Ganso',
      'Garca',
      'Gaviao',
      'Gralha',
      'Graveteiro',
      'Inhambu',
      'Jacu',
      'Joao de barro',
      'Loris',
      'Mergulhao',
      'Mergulho',
      'Papagaio',
      'Pato',
      'Pavao',
      'Pele',
      'Periquito',
      'Picapau',
      'Pintar roxo',
      'Pombo',
      'Quero quero',
      'Rouxinol',
      'Sabia',
      'Sanhaco',
      'Saracura',
      'Suiriri',
      'Ticotico',
      'Tucano',
      'Urubu',
      'Xexeu',
      'Zabele',
      'Zangao',
      'Aguia',
      'Condor andino',
      'Grifo',
      'Gaviao real',
      'Avestruz',
      'Falcao peregrino',
      'Corvo',
      'Pinguim',
      'Cegonha',
      'Tucano de bico preto',
      'Grou',
      'Colibri',
      'Pica pau',
      'Pica pau de cabeca amarela',
      'Gaviao carijo',
      'Tuiuiu',
      'Araponga',
      'Faisao',
      'Tentilhao',
      'Sabia laranjeira',
      'Soco boi',
      'Martim pescador',
      'Gralha azul',
      'Tico tico rei',
      'Tico tico',
      'Rouxinol',
      'Beija flor preto',
      'Pelicano',
      'Pardal',
      'Arapapa',
      'Tangara',
      'Pintassilgo',
      'Andorinhao',
      'Maritaca',
      'Pardal',
      'Periquito rei',
      'Saracura tres potes',
      'Joao bobo',
      'Anambe',
      'Zabele',
      'Tinamiformes',
      'Martim',
      'Codorniz',
      'Pica pau verde',
      'Canario',
      'Pintarroxo',
    ],
  };
};

export default Birds;
