const Birds = () => {
  return {
    aves: [
      'Aguia',
      'Albatroz',
      'Andorinha',
      'Anu',
      'Arara',
      'Beijaflor',
      'Bigodinho',
      'Caboclinho',
      'Canario',
      'Carcara',
      'Condor',
      'Coruja',
      'Curio',
      'Emu',
      'Falcao',
      'Flamingo',
      'Frango',
      'Gaivota',
      'Galo',
      'Ganso',
      'Garca',
      'Gaviao',
      'Gralha',
      'Graveteiro',
      'Inhambu',
      'Jacu',
      'Joaodebarro',
      'Loris',
      'Mergulhao',
      'Mergulho',
      'Papagaio',
      'Pato',
      'Pavao',
      'Pele',
      'Periquito',
      'Picapau',
      'Pintarroxo',
      'Pombo',
      'Queroquero',
      'Rouxinol',
      'Sabia',
      'Sanhaco',
      'Saracura',
      'Suiriri',
      'Ticotico',
      'Tucano',
      'Urubu',
      'Xexeu',
      'Zabele',
      'Zangao',
    ],
  };
};

export default Birds;
