const Marine = () => {
  return {
    marinhos: [
      'Abalone',
      'Arenque',
      'Arraia',
      'Atum',
      'Baiacu',
      'Baleia',
      'Barracuda',
      'Berbigao',
      'Besugo',
      'Bicuda',
      'Bonito',
      'Budiao',
      'Camarao',
      'Cangrejo',
      'Caranguejo',
      'Carapau',
      'Cavala',
      'Cherne',
      'Chocos',
      'Corvina',
      'Dourada',
      'Enguia',
      'Garoupa',
      'Golfinho',
      'Jaquetao',
      'Lagosta',
      'Linguado',
      'Lula',
      'Marlim',
      'Medusa',
      'Mexilhao',
      'Moreia',
      'Nautilo',
      'Ostra',
      'Paloco',
      'Pargo',
      'Pescada',
      'Polvo',
      'Raia',
      'Robalo',
      'Salmao',
      'Sardinha',
      'Sargo',
      'Sepia',
      'Siri',
      'Solha',
      'Tainha',
      'Tartaruga',
      'Tilapia',
      'Tubarao',
      'Xarroco',
      'Xareu',
      'Zaragateiro',
      'Albatroz',
      'Anemona do mar',
      'Boto',
      'Caracol marinho',
      'Cavalo marinho',
      'Camarao pistola',
      'Caramujo',
      'Estrela do mar',
      'Foca',
      'Leao marinho',
      'Morsa',
      'Narval',
      'Orca',
      'Pinguim',
      'Sereia',
      'Tartaruga marinha',
      'Tubarao martelo',
    ],
  };
};

export default Marine;
