const Sports = () => {
  return {
    esportes: [
      'Arco e Flecha',
      'Artes Marciais',
      'Atletismo',
      'Automobilismo',
      'Badminton',
      'Balonismo',
      'Basebol',
      'Basquetebol',
      'Biatlo',
      'Bilhar',
      'BMX',
      'Bocha',
      'Boliche',
      'Boxe',
      'Canoagem',
      'Capoeira',
      'Ciclismo',
      'Corfebol',
      'Corrida de Aventura',
      'Crossfit',
      'Criquete',
      'Curling',
      'Danca',
      'Esgrima',
      'Esqui',
      'Fisiculturismo',
      'Futebol',
      'Ginastica',
      'Golfe',
      'Handebol',
      'Hipismo',
      'Hoquei',
      'Iatismo',
      'Jiu jitsu',
      'Judo',
      'Karate',
      'Kitesurf',
      'Levantamento de Peso',
      'Luta Livre',
      'Mergulho',
      'Motocross',
      'Natacao',
      'Paraquedismo',
      'Parkour',
      'Patinagem',
      'Patinacao Artistica',
      'Polo Aquatico',
      'Rapel',
      'Rugbi',
      'Saltos Ornamentais',
      'Skate',
      'Snowboard',
      'Surfe',
      'Taekwondo',
      'Tenis',
      'Tenis de Mesa',
      'Tiro com Arco',
      'Triatlo',
      'Vela',
      'Volei',
      'Volei de Praia',
      'Wakeboard',
      'Windsurf',
      'Xadrez',
      'Yoga',
      'Zumba',
      'Bodyboard',
      'Maratona Aquatica',
      'Escalada',
      'Rafting',
      'Karting',
      'Esqui Aquatico',
      'Paraquedismo',
      'Raquetebol',
      'Slackline',
      'Squash',
      'Airsoft',
      'Polo',
      'Paddleboarding',
      'Bungee Jumping',
      'Acrobacias Aereas',
      'Acrobacia em Solo',
      'Patinacao de Velocidade',
      'Futebol Americano',
      'Hapkido',
      'Halterofilismo',
      'MMA',
      'Pancracio',
      'Golfe de Disco',
      'Ultimate Frisbee',
      'Softbol',
      'Surf de Remada',
      'Escalada em Arvores',
      'Tiro Esportivo',
      'Pentatlo Moderno',
      'Curling de Verao',
      'Golfe de Praia',
      'Arremesso de Machado',
      'Esqui Freestyle',
      'Korfball',
      'Futebol de Areia',
      'Powerlifting',
      'Dardos com Sopro',
      'Poker',
      'Sinuca',
      'Truco',
      'Domino',
      'Bowling',
      'Cricket',
      'Dardos',
      'Damas',
      'Frisbee',
      'Gamao',
      'Hoquei no Gelo',
      'Damas',
      'Mahjong',
      'Poquer',
      'Sinuca',
      'Truco',
      'Xadrez',
      'Yatzy',
    ],
  };
};

export default Sports;
